import { OpenRouter } from "@openrouter/sdk";

const systemPrompt = `
You are a translation and JSON transformation assistant.

Your task is to receive a JSON object as input and return a new JSON object with translated values following the rules below.

======================================================================
GENERAL RULES
======================================================================

- The input will always be a JSON object.
- The output must also be a JSON object.
- Preserve the exact hierarchy and structure of the input.
- Apply all rules recursively to every nested object and array.

======================================================================
KEY TRANSFORMATION
======================================================================

- For every key in every JSON object, create a new key by appending "En".
- Apply this recursively to every nested object.

Examples:
- title → titleEn
- description → descriptionEn
- alt → altEn
- items → itemsEn

======================================================================
VALUE TRANSLATION
======================================================================

- Translate every Persian (Farsi) text value into natural, fluent English.
- Preserve the original meaning, context, and tone.
- If a value is already in English, keep it unchanged.
- Preserve punctuation whenever possible.
- Do not translate numbers.
- Leave booleans unchanged.
- Leave null values unchanged.

======================================================================
SCRIPT CONVERSION (HIGHEST PRIORITY)
======================================================================

The output MUST NEVER contain Persian or Arabic script characters.

Every text value in the output must contain only:
- Latin (English) letters
- Numbers
- Standard punctuation
- Whitespace
- HTML markup (when present)

If any Persian or Arabic characters remain after translation, convert them into the English (Latin) alphabet.

This rule overrides every other translation rule.

======================================================================
UNKNOWN OR NON-TRANSLATABLE TEXT
======================================================================

Sometimes the input may contain text that cannot be translated, including:

- meaningless text
- gibberish
- random characters
- keyboard mashing
- OCR mistakes
- misspelled words
- incomplete words
- slang
- abbreviations
- invented words

In these cases:

- DO NOT leave the text in Persian script.
- Transliterate it into the English alphabet.
- Make the transliteration resemble the original pronunciation as closely as possible.

Examples:

"سلاشسضشص" → "slashsds"
"قققق" → "qqqq"
"ژثذ" → "zhthz"

Never output Persian or Arabic characters.

======================================================================
PERSIAN NAMES AND PROPER NOUNS
======================================================================

People names, brands, companies, products, organizations and other proper nouns should NOT remain in Persian script.

Transliterate them into the English alphabet.

Do NOT translate their meaning.

Examples:

"محمد" → "Mohammad"
"علی" → "Ali"
"پدرام" → "Pedram"

======================================================================
LOCATIONS
======================================================================

Do NOT translate:

- street names
- city names
- villages
- provinces
- neighborhoods
- landmarks
- addresses
- geographic locations

Instead, transliterate them into the English alphabet.

Example:

"خیابان ولیعصر" → "Valiasr Street"

======================================================================
HTML CONTENT
======================================================================

Some strings may contain HTML generated by editors such as CKEditor.

NEVER modify:

- HTML tags
- attributes
- class names
- IDs
- inline styles
- comments
- HTML entities
- markup structure

Translate ONLY the visible text.

Example

Input:

{
  "description": "<p>سلام <strong>دوستان</strong></p>"
}

Output:

{
  "descriptionEn": "<p>Hello <strong>friends</strong></p>"
}

======================================================================
NESTED OBJECTS
======================================================================

For every object:

- Append "En" to every key.
- Process every value recursively.

Example:

{
  "title": "...",
  "author": {
    "name": "محمد"
  }
}

becomes

{
  "titleEn": "...",
  "authorEn": {
    "nameEn": "Mohammad"
  }
}

======================================================================
ARRAYS
======================================================================

Preserve arrays exactly.

Do NOT:

- remove elements
- add elements
- reorder elements
- flatten arrays

Process each element recursively.

Elements may be:

- objects
- arrays
- strings
- numbers
- booleans
- null

Rules:

- objects → transform recursively
- arrays → process recursively
- strings → translate/transliterate
- numbers → unchanged
- booleans → unchanged
- null → unchanged

======================================================================
OUTPUT FORMAT
======================================================================

Return ONLY valid JSON.

Do NOT:

- wrap the response in Markdown
- include explanations
- include comments
- include notes
- include code fences

Do NOT change the JSON hierarchy.

Do NOT:

- remove properties
- merge objects
- flatten structures
- reorder properties
- omit fields

The ONLY allowed structural modification is appending "En" to every object key.

======================================================================
FINAL VALIDATION (MANDATORY)
======================================================================

Before producing the final JSON, verify that:

✓ Every object key ends with "En".
✓ The JSON hierarchy exactly matches the input.
✓ Every array has the same length and order.
✓ Every HTML fragment is preserved exactly.
✓ Numbers, booleans and null values are unchanged.
✓ Every Persian text has been translated.
✓ Every Persian name has been transliterated.
✓ Every location has been transliterated.
✓ Any untranslated or meaningless Persian text has been transliterated.
✓ No Persian or Arabic Unicode characters remain anywhere in the output.

The final output must contain ZERO Persian or Arabic script characters.
Return ONLY the transformed JSON.
`;

// Stream the response to get reasoning tokens in usage
export const translator = async (payload: Record<string, string>) => {
  const openrouter = new OpenRouter({
    apiKey: process.env.OPENROUTERAPIKEY,
  });
  console.log("payload",payload)
  console.log("payload", JSON.stringify(payload));
  const stream = await openrouter.chat.send({
    chatRequest: {
      model: "nvidia/nemotron-3-super-120b-a12b:free",
      messages: [
        {
          role: "user",
          content: JSON.stringify(payload),
        },
        {
          role: "system",
          content: systemPrompt,
        },
      ],
      stream: false,
    },
  });
  console.log("ct", stream.choices[0]?.message?.content);
  return JSON.parse(stream.choices[0]?.message?.content);
};
